# Generated by Django 2.2.6 on 2019-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_title', models.CharField(max_length=200)),
                ('quest_text', models.TextField()),
            ],
        ),
    ]
