# Generated by Django 2.2.6 on 2019-10-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_quest_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
