# Generated by Django 2.2.6 on 2019-10-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='quest_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='quest_thread',
            field=models.TextField(default="Couldn't retrieve the thread"),
        ),
        migrations.AddField(
            model_name='question',
            name='quest_votes',
            field=models.IntegerField(default=0),
        ),
    ]
