# Generated by Django 2.2.6 on 2019-10-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
