# Generated by Django 2.2.6 on 2019-10-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='address',
            field=models.TextField(default="Couldn't retrieve the address"),
        ),
    ]
